name: Preferred Home Lending
favicon: null
layout_spectrum: 0.7658792538568377
typography_spectrum: 0.6750010328833014
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.24060125625692308
  lightness: 0.21427215007133782
  saturation: 0.24460598942823708
  rhythmicContrast: 0.167898862157017
purpose: []
